import TAC from "./TAC";

export const metadata = {
  title: "Terms and Conditions : MuniTrack",
  description: "Generated by create next app",
};

export default function Page() {
  return <TAC />;
}
