import DriveCreate from "./DriveCreate";

export const metadata = {
    title: "Create Drive : MuniTrack",
    description: "Generated by create next app",
  };


export default function Page(){
    return(
        <DriveCreate/>
    )
}