
export const metadata = {
    title: "Chat : MuniTrack",
    description: "Generated by create next app",
  };

export default function Page(){
    return(
        <div>
            <nav className="bg-gray-700 py-1 px-2 uppercase text-center"> Chatting ...</nav>
            <div>
                i am chat page
            </div>
        </div>
    )
}