import Feedback from "./Feedback";

export const metadata = {
  title: "Feedback : MuniTrack",
  description: "Generated by create next app",
};

export default function Page() {
  return <Feedback />;
}
