import Details from "./Details"

export const metadata = {
    title: "issue/issuename : MuniTrack",
    description: "Generated by create next app",
  };

export default function Issue({params}){
    let {issueid} = params
    return(
        <Details name={issueid} />
    )
}