import Add from "./Add";


export const metadata = {
    title: "Upload Issue : MuniTrack",
    description: "Generated by create next app",
  };

export default function Page(){
    return(
        <Add/>
    )
}