import HomePost from "./IssueShow";

export const metadata = {
    title: "Issue : MuniTrack",
    description: "Generated by create next app",
  };


export default function Page(){
    return(
        <HomePost/>
    )
}