import Google from "./Google";


export const metadata = {
    title: "Login : MuniTrack",
    description: "Generated by create next app",
  };

export default function Page(){
    return(
        <Google/>
    )
}