import Upload from "./Upload";

export const metadata = {
    title: "Drive : MuniTrack",
    description: "Generated by create next app",
  };

export default function Page(){
    return(
        <Upload/>
    )
}