
export const metadata = {
    title: "Search : MuniTrack",
    description: "Generated by create next app",
  };

export default function Page(){
    return(
        <div>
            I am search Page
        </div>
    )
}