import Search from "./Search";

export const metadata = {
    title: "Search : MuniTrack",
    description: "Generated by create next app",
  };

export default function Page(){
    return(
        <Search/>
    )
}