export const metadata = {
  title: "Login : MuniTrack",
  description: "Generated by create next app",
};

export default function Page(){
    return(
        <div className="min-h-screen">Account</div>
    )
}