import Account from "./Account";

export const metadata = {
  title: "Account : MuniTrack",
  description: "Generated by create next app",
};

export default function Page(){
    return(
      <Account/>
    )
}