import Register from "./Register";

export const metadata = {
    title: "Register : MuniTrack",
    description: "Generated by create next app",
  };

export default function Page(){
    return(
        <Register/>
    )
}